/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIChat: typeof import('./src/components/AIChat.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    DashboardCards: typeof import('./src/components/DashboardCards.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NFCScanner: typeof import('./src/components/NFCScanner.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WarningItemsTable: typeof import('./src/components/WarningItemsTable.vue')['default']
  }
}
