/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiChat: typeof import('./src/components/AiChat.vue')['default']
    AIChat: typeof import('./src/components/AiChat.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Dashboard: typeof import('./src/components/Dashboard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Locker: typeof import('./src/components/Locker.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Logs: typeof import('./src/components/Logs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Scanner: typeof import('./src/components/Scanner.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Warnings: typeof import('./src/components/Warnings.vue')['default']
  }
}
